### ISSUE TITLE
some classes are missing

### ISSUE THREAD

**Issue by naimavahab** [BMKEG/lapdftext#33] opened 2017-12-14 13:19 UTC
import edu.isi.bmkeg.utils.Converters;
import edu.isi.bmkeg.utils.xml.XmlBindingTools; 

these seems to be missing when i use blockify/blockifyClassify

**Comment by naimavahab** [comment] 2017-12-15 06:31
any updates for this issue  pls?

**Comment by TanujRohatgi** [comment] 2017-12-15 08:15
Could you please share the pom.xml you're using?
Also please mention if you're referring to the parent-pom.xml or not?
Off the top of my head i think you're not referring to the parent-pom.xml ( or some issue is there with your parent pom.xml) because the dependencies you've mentioned are resolved in the parent-pom.xml

**Comment by naimavahab** [comment] 2017-12-15 09:31
[lapdfPom.txt](https://github.com/BMKEG/lapdftext/files/1562176/lapdfPom.txt)
[pomfileParent.txt](https://github.com/BMKEG/lapdftext/files/1562177/pomfileParent.txt)
Please find the POM files.. 
These classes Converters , XmlBindingTools are expected to present in the respective classes .. but they are not found

**Comment by TanujRohatgi** [comment] 2017-12-15 11:45
the pom looks fine, assuming that the relative path you've provided is correct it should ideally work.
Could you please check this issue ([https://github.com/BMKEG/lapdftext/issues/29]) regarding how to build the latest versions, just try what i've suggested in the last comment once.

In the mean time, it would be helpful if you could provide any stack traces of a detailed description of your problem so i can try and reproduce it?

**Comment by naimavahab** [comment] 2017-12-15 12:20
[pomResult.txt](https://github.com/BMKEG/lapdftext/files/1562624/pomResult.txt)

The console comes like this after i build pom for lapdf .. 

Although the maven build shows success , main of the libraries are not getting imported like log4j also ...

**Comment by naimavahab** [comment] 2017-12-18 09:31
@TanujRohatgi  hi.. any updates..?

**Comment by naimavahab** [comment] 2017-12-19 06:03
hi, when i tried building the complete LaPdfTextProject  that time those classes were not getting dependencies. After building complete parent the individual separate project like lapdftext were able to run although the dependency problems existed in parent one. Also the trove needed 2.0.2 and jsi 1.0.0 to compile the project successfully.. The images of parent and individual project are given below. 
![parent](https://user-images.githubusercontent.com/13636783/34142981-270bb8f6-e482-11e7-9df3-23614f23fba2.png)
![lapdf](https://user-images.githubusercontent.com/13636783/34142982-273e4f6e-e482-11e7-839f-08261e812637.png)
Thank you @TanujRohatgi for the help 
Thus closing this issue

**Closed** 2017-12-19 06:32 UTC
